### ISSUE TITLE
certificate for https://www.tortall.net has expired

### ISSUE THREAD

**Issue by joshrabinowitz** [yasm/yasm#106]
the certificate for https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz has expired. Firefox reports:

https://www.tortall.net uses an invalid security certificate. The certificate expired on June 5, 2018, 4:33 AM. The current time is June 5, 2018, 8:10 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

See also: https://github.com/HandBrake/HandBrake/issues/1390

**Comment by MichaelUrman** [comment]
As another potential workaround, could HandBreak use the GitHub hosted releases? https://github.com/yasm/yasm/archive/v1.3.0.tar.gz downloads fine for me without certificate errors.

**Comment by PeterJohnson** [comment]
Fixed (for some reason the webserver needed to be restarted to grab the new cert).

**Comment by nimrod-becker** [comment]
Happens again (same as mentioned in https://github.com/Nemocas/Nemo.jl/issues/605).

Tried to download the version from github (https://github.com/yasm/yasm/archive/v1.3.0.tar.gz), but it does not contain the ```configure```

Any ideas or docs on how to use the package directly from github?

**Comment by heiderich** [comment]
@nimrod-becker Run `./autogen.sh` to create `configure`.

**Comment by nimrod-becker** [comment]
Ye, found it earlier on, updated the new issue as well . 
Thanks.

**Comment by heiderich** [comment]
Oh, I did not notice that issue. For the reference: #135
