### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by 360CodeSafe** [yasm/yasm#113]
tools/genmacro/genmacro.c 

in line 59: str = malloc(MAXLINE); // memory is allocated

in line 94:   return EXIT_FAILURE;// function returned and potential leak of memory pointerd to by 'str'.

**Comment by dsamarin** [comment]
Hey robot, when the program ends all of the memory is freed by the operating system. Potentially, the variable could be defined as `char str[MAXLINE];`

**Comment by 360CodeSafe** [comment]
Yea, make sense! Since the memory leak occurred in `main()`, we did not lose the track of `str` and the memory allocation was not in loop, strictly speaking, there is no issue!

The analyzer should suppress these warnings :)
