### ISSUE TITLE
Why are windows .exe 60% larger when I build vs release build?

### ISSUE THREAD

**Issue by TBOpen** [yasm/yasm#127]
I used VS2017, built from the latest source, and the release sizes were 60% larger than the ones pre-built on the original 1.3.0 release.  Looking at the commits, it doesn't look like 300+K of code changes were made and doesn't look like the released .exe versions are compressed with upx or mpress.  

I need the updated versions to fix problems with vsyasm not allowing Win32 parameter (case sensitivity issue).   Is this safe or is something fishy going on?

?

**Comment by BrianGladman** [comment]
Although I have not looked at the reasons for this in any detail, I do not think it is an issue you need to worry about.

**Comment by TBOpen** [comment]
I looked to see if the release link had debug on, and lo and behold it did, turned it off, now it's more like 80 to 120K different in size.  More reasonable.  Just expected the release build to match released binary.
