### ISSUE TITLE
How to install it on Ubuntu 16.04?

### ISSUE THREAD

**Issue by evandrocoan** [yasm/yasm#131]
```
root@evandro-pc:~# apt-get install yasm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package yasm
root@evandro-pc:~# apt-get install nasm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nasm
```

**Comment by evandrocoan** [comment]
I fixed it by adding these to my `/etc/apt/sources.list` file:
```
#------------------------------------------------------------------------------#
#                            OFFICIAL UBUNTU REPOS                             #
#------------------------------------------------------------------------------#


###### Ubuntu Main Repos
deb http://55.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse 
deb-src http://55.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse 

###### Ubuntu Update Repos
deb http://55.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse 
deb http://55.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse 
deb http://55.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse 
deb http://55.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse 
deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse 
deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse 
deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse 
deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse 

###### Ubuntu Partner Repo
deb http://archive.canonical.com/ubuntu xenial partner
deb-src http://archive.canonical.com/ubuntu xenial partner
```

**Comment by RussQuan** [comment]
> ###### Ubuntu Main Repos
> deb http://55.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse 
> deb-src http://55.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse 
> 
> ###### Ubuntu Update Repos
> deb http://55.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse 
> deb http://55.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse 
> deb http://55.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse 
> deb http://55.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse 
> deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse 
> deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse 
> deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse 
> deb-src http://55.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse 
> 
> ###### Ubuntu Partner Repo
> deb http://archive.canonical.com/ubuntu xenial partner
> deb-src http://archive.canonical.com/ubuntu xenial partner

it works for me on ubuntu16.04 !!!!
Thank you so much !
