### ISSUE TITLE
Yasm does not affect "dword" and "strict" keywords in push command on arm host

### ISSUE THREAD

**Issue by aristarh2704** [yasm/yasm#139]
I'm tried compile this code:
```
bits 32
push ebx
push dword ebx
push strict dword ebx
```
but llvm-objdump shows that assembler emit pushw instruction.
If I run compiler on x86 host, it works correctly.

**Comment by PeterJohnson** [comment]
Yasm's behavior does not change on different hosts; you'll get the exact same output.  I think if you look at the files yasm outputs on each host, the files will be identical, and it's something about the configuration of llvm-objdump that's different between the two hosts that is causing it to disassemble differently.  I verified this myself by running `yasm -f bin` on the above test code on both an arm64 machine and on an x86-64 machine; on both machines the binary output contains 53 53 53.

**Comment by aristarh2704** [comment]
I found that yasm package for my distro is broken, I compile it from source and it work properly.
