### ISSUE TITLE
Allow including target system information in objects on macOS.

### ISSUE THREAD

**Issue by john-preston** [yasm/yasm#141]
I'm using macOS 10.15 and Xcode 11.2.1 and building ffmpeg on macOS and then link it to my project targeting macOS 10.12. When linking the linker gives such warnings:
```
ld: warning: building for macOS, but linking in object file (/Users/preston/Telegram/Libraries/macos/ffmpeg/libswscale/libswscale.a(input.o)) built for free standing
```
For all object files that were built using YASM.

For C and C++ sources additional compiler options are passed to Apple Clang: "-mmacosx-version-min=10.12" and this removes such problems for object files built from C / C++ sources. I guess it puts something like this in the object file:
```
Load command 1
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.12
      sdk 10.15
```
and this information is read by the linker and it doesn't complain.

Is it possible to add a flag to pass on macOS to YASM so that it will write such section as well? Those warnings are noisy and it seems they can't be disabled.

Other compilers (Crystal, Go, D) have (or had) this problem as well, see: https://github.com/golang/go/issues/33214#issuecomment-541353859

**Comment by tmm1** [comment]
The new version of `LC_VERSION_MIN_*` is `LC_BUILD_VERSION`, which contains a `platform` field to differentiate between ios/tvos/macos and the new iosmac (catalyst)

```
       cmd LC_BUILD_VERSION
   cmdsize 24
  platform 6
       sdk 13.1
     minos 13.0
```

**Comment by tmm1** [comment]
In addition to the `LC_BUILD_VERSION` mach-o load command, an `__LLVM,__asm` marker is also required to allow assembled objects to be used in bitcode-required xcode builds. See https://github.com/golang/go/issues/22395#issuecomment-472638175 for more details and https://go-review.googlesource.com/c/go/+/168320/ for the implementation used in the golang compiler.

**Comment by john-preston** [comment]
This issue is really pressing now, when Xcode 12 changed this warning to an error. There is no way to link the yasm-compiled object files with macOS project anymore :(

https://stackoverflow.com/questions/63970784/xcode-12-how-to-link-against-object-files-built-for-free-standing

**Comment by mbarriault** [comment]
Is there any update on this issue? We're hitting it with ffmpeg as well and it's a real show-stopper.

**Comment by PeterJohnson** [comment]
Implementing this is fairly straightforward.  It feels more stylistically consistent to set the version through a directive in the assembly file rather than via a command line option.  Would this be acceptable for your intended use case?

**Comment by mbarriault** [comment]
Apologies for delay in getting back. I'm rather out of my element here when it comes to assembly, we just need to be able to link ffmpeg using Xcode 12. Does this `[buildversion...]` line just go in the .asm files?

**Comment by PeterJohnson** [comment]
Yes, it goes into the .asm file, so no build tool changes required.

**Comment by konradglas** [comment]
@mbarriault can I ask how you finally got it to work? Adding the ```[buildversion ...]``` section tells me that it is not recognized by yasm (also with the -lvmasm option) ... Thank you :)
