### ISSUE TITLE
make check has 2 failed tests (linux amd64)

### ISSUE THREAD

**Issue by lulcat** [yasm/yasm#157]
Hi there. when running make check, I got 2/44 tests failed:

1. FAIL: modules/objfmts/elf/tests/amd64/elf_amd64_test.sh
=======================================================

Test elf_amd64_test: O... +3-1/4 75%
 ** O: elf-rip did not match object file!

2. FAIL: modules/objfmts/elf/tests/gas64/elf_gas64_test.sh
=======================================================

Test elf_gas64_test: O... +3-1/4 75%
 ** O: crosssect did not match object file!

**Comment by lulcat** [comment]
Ok, thanks, I will try that, I have totally forgotten this but once I get time I will check it. (and hopefully can give an update if ok or not). :)

**Comment by justinkb** [comment]
Exactly. This bug has existed for 4 years or so
