### ISSUE TITLE
GAS: set inside repm crashes

### ISSUE THREAD

**Issue by Fighter19** [yasm/yasm#176]
Using this test file to run the GAS-style preprocessor, yasm crashes:
```
.set counter, 0
.macro REPEATER_2 count=5
.rept \count
    .set counter, counter+1
.endr
.endm 

REPEATER_2
```
Command line:
```bash
yasm -r gas -e yasm_crash.S -o yasm_crash.i
```
Output:
```
free(): invalid pointer
```
Backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff75e8921 in __GI_abort () at abort.c:79
#2  0x00007ffff7631967 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff775eb0d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff76389da in malloc_printerr (str=str@entry=0x7ffff775cd08 "free(): invalid pointer") at malloc.c:5342
#4  0x00007ffff763ff0c in _int_free (have_lock=0, p=0x55555560eca4, av=0x7ffff7993c40 <main_arena>) at malloc.c:4167
#5  __GI___libc_free (mem=0x55555560ecb4) at malloc.c:3134
#6  0x00007ffff7bc904a in def_xfree (p=0x55555560ecb4) at ./yasm/libyasm/xmalloc.c:113
#7  0x00007ffff7334c90 in eval_rept (pp=0x55555560cac0, unused=0, arg1=0x55555560ec76 "5")
    at ./yasm/modules/preprocs/gas/gas-preproc.c:1002
#8  0x00007ffff733563d in process_line (pp=0x55555560cac0, line_ptr=0x7fffffffd608)
    at ./yasm/modules/preprocs/gas/gas-preproc.c:1203
#9  0x00007ffff7335d63 in gas_preproc_get_line (preproc=0x55555560cac0)
    at ./yasm/modules/preprocs/gas/gas-preproc.c:1336
#10 0x0000555555403261 in do_preproc_only () at ./yasm/frontends/yasm/yasm.c:325
#11 0x000055555540417f in main (argc=7, argv=0x7fffffffd798) at ./yasm/frontends/yasm/yasm.c:728
```

**Comment by Fighter19** [comment]
Appears to be a double free of bline->line

**Comment by Fighter19** [comment]
This error is caused by https://github.com/yasm/yasm/blob/009450c7ad4d425fa5a10ac4bd6efbd25248d823/modules/preprocs/gas/gas-preproc.c#L949

Using the "tab" before set, results in yasm freeing the wrong pointer.

**Comment by arizvisa** [comment]
> Appears to be a double free of bline->line

...and where is bline->line being allocated before it goes out of scope? What token is causing it to be released? You need to identify the logic that's causing it to be double-referenced... before spamming a bug tracker.

**Comment by Fighter19** [comment]
I'm sorry, apparently I didn't document the issue well enough. Closed it because apparently it doesn't provide enough information for a dev to actually fix it.

**Comment by arizvisa** [comment]
Perfect. Thanks you.

**Comment by PeterJohnson** [comment]
Reopening since this is a real bug.  A reproducible test case should be sufficient to make a bug report.  While more analysis is of course helpful to the developer, it's not the bug reporter's job to isolate an issue all the way to a patch to fix it.

Sorry for the lack of activity here; I've not been paying as much attention to yasm in recent years due to other projects.

**Comment by arizvisa** [comment]
> Reopening since this is a real bug. A reproducible test case should be sufficient to make a bug report. While more analysis is of course helpful to the developer, it's not the bug reporter's job to isolate an issue all the way to a patch to fix it.

Well ~31 of  these types of bugs have not been triaged yet. Not only that, but these have all been submitted as security issues and should get CVEs..as the papers that reference the issues use them as validation for their "research". However you choose to prioritize them, though.

However, rather than going through pounding gophers in the parser and feeding the macro preprocessor absurd numbers of arguments, there's just a whole bunch of other things of more value that can be easier maintained with the little resources this project has. Fixing slews of bugs effectively typically requires rearchitecture and resdesign, and isn't practical as both motivation and time are major factors in those types of efforts. Nonetheless, I appreciate your kindness to these academic security researchers that rarely (if ever) commit code.

**Comment by Fighter19** [comment]
I have nothing to do with any security researcher, nor did I mark this bug as a security bug, nor did I pass an incredible amount of arguments to any macro preprocessor.

I simply stumbled across this issue and tried to provide as much help as I could (I played around with this bug for 2+ hours after I encountered it, and now about 1-2 more hours to make sure everything's working fine).
In this case I wanted to use yasm as a preprocessor for another assembler that had no macros
and found that it would be great to at least document the bug so that people that might encounter it, know when it's fixed and that it exists.
If I find any trivial bugs, I tend to fix them myself and do a PR or to avoid copyright issues for the project (e.g when changing licenses), I suggest abstract changes in words that a maintainer can then validate and implement.

Knowing that solving memory related issues is non-trivial I shy away from suggesting any specific solutions as I might not know enough about the underlying architecture to ensure safe usage. Neither should I have to. I'm only the user. In this case seeing that other functions worked in the same way, I'm confident the PR I made is correct and helps to improve the situation (assuming that the other code parts are correctly written).

The changes are of course tested by me with the aforementioned file.

This was completely voluntary help provided in hope to safe someone else's time.

I see the other issues, I get where you're coming from, but at the same time it's more than obvious, that I did not create this issue for any other intention. If you visited my profile you could see that most of the stuff I'm involved with has nothing to do with security (rather with my personal hobbies). If you looked at the messages you could see the time I invested for each statement and see that I bothered creating a minimum working example based on the real usage I had for the preprocessor. (Why is it called REPEATER_2? Certainly not because there wasn't a REPEATER macro before)

Also I don't see how you're contributing to this project currently.
You dare call my posts spamming, while you yourself just write:
"Yep..."
https://github.com/yasm/yasm/issues/150#issuecomment-956161057

But yes, I will use the editing feature more often onwards.
I thought it would be great to ensure that people that are subscribed to the issue get instant notifications as long as I'm working on it (as a kind of co-working thing). But I acknowledge that it's probably more annoying than helpful.

**Comment by Fighter19** [comment]
Please review
https://github.com/yasm/yasm/pull/189
so we can hopefully close this issue.
