### ISSUE TITLE
Certificate for https://www.tortall.net has expired, again

### ISSUE THREAD

**Issue by tylerdhoward** [yasm/yasm#182]
This seems to have occurred again as of 8 days ago: https://github.com/yasm/yasm/issues/106

I was trying to install the ffmpeg:x86-windows package via vcpkg on my Windows machine, which depends on yasm and currently points to https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe

https://github.com/microsoft/vcpkg/blob/8886d85ad0215a7f30459f5a3c495a0f7c4d6a88/scripts/cmake/vcpkg_find_acquire_program.cmake#L91

```
[DEBUG] Downloading https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe
Failed to download from mirror set:
https://www.tortall.net/projects/yasm/snapshots/v1.3.0.6.g1962/yasm-1.3.0.6.g1962.exe: WinHttpSendRequest() failed: 12175
```

**Comment by PeterJohnson** [comment]
I'm working on it.  It will probably be a couple of days before it's fixed.

**Comment by PeterJohnson** [comment]
Should be fixed now, just need DNS to propagate.

**Comment by nikwen** [comment]
@PeterJohnson Thanks for this great project!

Firefox and curl don't accept the certificate for the source tarball: https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz

I can use HTTP in the meantime but it would be really cool to have a working cert for that download, too, as I reference it in my build scripts.

**Comment by PeterJohnson** [comment]
DNS might not have propagated yet.  I’ll get the certificate copies over to the old server.  Also, for the main 1.3.0 release, you can also grab that from GitHub releases instead: https://github.com/yasm/yasm/releases/tag/v1.3.0

**Comment by nikwen** [comment]
> DNS might not have propagated yet. I’ll get the certificate copies over to the old server.

Not sure if it's a propagation issue. The cert is from Fri, 06 Aug 2021.

Firefox complains about the following:

> Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for www.tortall.net. The certificate is only valid for the following names: tortall.com, tortall.net, tortall.org
>
> Error code: SSL_ERROR_BAD_CERT_DOMAIN

Apparently, a cert for `tortall.net` is not valid for `www.tortall.net`.

> Also, for the main 1.3.0 release, you can also grab that from GitHub releases instead: https://github.com/yasm/yasm/releases/tag/v1.3.0

That's a really good tip. Thank you! I changed my script.

If you want to save some bandwidth, you can get the FFmpeg wiki updated to reference the GitHub release, too: https://trac.ffmpeg.org/wiki/CompilationGuide/Centos#Yasm. That's where I was coming from.

**Comment by PeterJohnson** [comment]
Fixed the certificate issue.

**Comment by nikwen** [comment]
Thank you! I can confirm it's fixed. 👍
