### ISSUE TITLE
Cert Expired www.tortall.net

### ISSUE THREAD

**Issue by publicarray** [yasm/yasm#190]
Hi there, I was unable to download a release due to an expired certificate  http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz

![Screenshot from 2021-11-10 23-32-16](https://user-images.githubusercontent.com/5497998/141113881-253d154b-9588-4565-9084-9e7e2755f2d7.png)

@PeterJohnson

**Comment by PeterJohnson** [comment]
Ugh, it appears certbot didn't do its job.  Will fix tonight.

**Comment by PeterJohnson** [comment]
Note you can download from GitHub releases instead.

**Comment by PeterJohnson** [comment]
Should be fixed.

**Comment by publicarray** [comment]
Thanks :+1:  FYI: you are no longer redirecting HTTP to HTTPS
