### ISSUE TITLE
yasm-tool[core] is only supported on 'native & !uwp'

### ISSUE THREAD

**Issue by szhllyyl** [yasm/yasm#193]
enviroment:win10   vs2019（MSVC140, 141）
![error](https://user-images.githubusercontent.com/40573733/142796468-2213aef9-57db-49a8-905c-f0bff5fb29a2.png)

**Comment by MichaelUrman** [comment]
I see you've filed microsoft/vcpkg#21592 which is probably the right place to start. If the end result identifies an incidental dependency on an API that UWP doesn't support, follow up here with the specifics and Yasm can decide whether to make changes to enable UWP support.

**Comment by szhllyyl** [comment]
yes,indeed.if microsoft/vcpkg#21592 works，I will close the issue，thank u for your reply。

**Comment by LearnToStick** [comment]
I met the same problem,how did you solve it?
