### ISSUE TITLE
segmentation fault on MacOS Monterey 12.2

### ISSUE THREAD

**Issue by ggavryly** [yasm/yasm#199]
Trying build [libdav1d](https://code.videolan.org/videolan/dav1d) asm source for arm
Here's command i use "yasm -f elf64 -p gas dav1d/src
and then I catch an error
<img width="543" alt="SegfaultMacos" src="https://user-images.githubusercontent.com/45670849/187673129-56ead6fe-784b-41bb-80c7-cd7089e6ee80.png">

Where is the error?

**Comment by PeterJohnson** [comment]
Well, it shouldn't segfault (instead report an error), but yasm isn't going to be able to assemble that file, as it doesn't have support for ARM processors (that source file is for 64-bit ARM).

**Comment by ggavryly** [comment]
Understood, tnx
