### ISSUE TITLE
differences from nasm and which one to use?

### ISSUE THREAD

**Issue by goyalyashpal** [yasm/yasm#245]
hi!

* i am looking for some alternate to the Turbo Assembled (tasm)
* for doing the practical for the subject of MicroProcessors 8086 (so, i want to see the value of registers, flags, segments etc)
* using VSCodium or some dedicated IDE.

I found yasm via [alternativeto][yasm-alt2] & i have read the [yasm-site] but i can't find which one to use.

[yasm-site]: http://yasm.tortall.net
[yasm-alt2]: https://alternativeto.net/browse/search/?q=nasm#item-3949c529-0955-e211-9c6a-0025902c7e73

**Comment by AdamMajer** [comment]
From the documentation, it looks like yasm was a fork of nasm because nasm wasn't being maintained. Then nasm for the features that yasm implemented.

I would say you could see if you can use either or both. There should not be much difference.
