### ISSUE TITLE
`error: warnings being treated as errors`

### ISSUE THREAD

**Issue by and3rson** [yasm/yasm#255]
This seems to appear every time I pass `-Werror` to yasm. It not only seems redundant, but it also makes it harder to visually identify any actual errors. What's the intention of this message? Is it possible to suppress it? `nasm` doesn't seem to print this.

**Comment by PeterJohnson** [comment]
Sure!

**Comment by and3rson** [comment]
Actually, I just checked out the latest code from this repo and it looks like this has already been fixed: this banner is only shown when there is at least one warning. So if there are no warnings - the banner is not shown.
This looks good to me, and I'm OK with seeing this banner when there are actual errors. :)
